from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon


class SubWindowLancamentos(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.subLan = QtWidgets.QWidget()
        self.subLan.setEnabled(True)
        self.subLan.setStyleSheet("")
        self.subLan.setObjectName("subLan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subLan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLan = QtWidgets.QTableWidget(self.subLan)
        self.gridLan.setObjectName("gridLan")
        self.gridLan.setColumnCount(13)
        self.gridLan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridLan.setHorizontalHeaderItem(12, item)
        self.gridLan.horizontalHeader().setVisible(True)
        self.gridLan.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLan.horizontalHeader().setDefaultSectionSize(120)
        self.gridLan.horizontalHeader().setHighlightSections(True)
        self.gridLan.horizontalHeader().setMinimumSectionSize(120)
        self.gridLan.horizontalHeader().setSortIndicatorShown(False)
        self.gridLan.horizontalHeader().setStretchLastSection(False)
        self.gridLan.verticalHeader().setHighlightSections(True)
        self.verticalLayout_2.addWidget(self.gridLan)
        self.fraBotoesLan = QtWidgets.QFrame(self.subLan)
        self.fraBotoesLan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBotoesLan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBotoesLan.setObjectName("fraBotoesLan")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fraBotoesLan)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnInserirLan = QtWidgets.QPushButton(self.fraBotoesLan)
        self.btnInserirLan.setMinimumSize(QtCore.QSize(48, 48))
        self.btnInserirLan.setMaximumSize(QtCore.QSize(48, 48))
        self.btnInserirLan.setStyleSheet("background-color: transparent; \n"
                                         "border: none;")
        self.btnInserirLan.setText("")
        self.btnInserirLan.setIcon(QIcon("icons/2x/insert.png"))
        self.btnInserirLan.setIconSize(QtCore.QSize(48, 48))
        self.btnInserirLan.setObjectName("btnInserirLan")
        self.horizontalLayout_6.addWidget(self.btnInserirLan)
        self.btnEditarLan = QtWidgets.QPushButton(self.fraBotoesLan)
        self.btnEditarLan.setMinimumSize(QtCore.QSize(48, 48))
        self.btnEditarLan.setStyleSheet("background-color: transparent; \n"
                                        "border: none;")
        self.btnEditarLan.setText("")
        self.btnEditarLan.setIcon(QIcon("icons/2x/edit.png"))
        self.btnEditarLan.setIconSize(QtCore.QSize(36, 36))
        self.btnEditarLan.setObjectName("btnEditarLan")
        self.horizontalLayout_6.addWidget(self.btnEditarLan)
        self.btnExcluirLan = QtWidgets.QPushButton(self.fraBotoesLan)
        self.btnExcluirLan.setMinimumSize(QtCore.QSize(48, 48))
        self.btnExcluirLan.setStyleSheet("background-color: transparent; \n"
                                         "border: none;")
        self.btnExcluirLan.setText("")
        self.btnExcluirLan.setIcon(QIcon("icons/2x/delete.png"))
        self.btnExcluirLan.setIconSize(QtCore.QSize(36, 36))
        self.btnExcluirLan.setObjectName("btnExcluirLan")
        self.horizontalLayout_6.addWidget(self.btnExcluirLan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnFecharLan = QtWidgets.QPushButton(self.fraBotoesLan)
        self.btnFecharLan.setMinimumSize(QtCore.QSize(48, 48))
        self.btnFecharLan.setMaximumSize(QtCore.QSize(48, 48))
        self.btnFecharLan.setStyleSheet("background-color: transparent; \n"
                                        "border: none;")
        self.btnFecharLan.setText("")
        self.btnFecharLan.setIcon(QIcon("icons/2x/close.png"))
        self.btnFecharLan.setIconSize(QtCore.QSize(40, 40))
        self.btnFecharLan.setObjectName("btnFecharLan")
        self.horizontalLayout_6.addWidget(self.btnFecharLan)
        self.verticalLayout_2.addWidget(self.fraBotoesLan)

        _translate = QtCore.QCoreApplication.translate
        self.subLan.setWindowTitle(_translate("MainWindow", "Lançamentos"))
        item = self.gridLan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Código"))
        item = self.gridLan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data do lançamento"))
        item = self.gridLan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Operação"))
        item = self.gridLan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.gridLan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Código do Item"))
        item = self.gridLan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Item"))
        item = self.gridLan.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Quantidade"))
        item = self.gridLan.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Código do Cliente"))
        item = self.gridLan.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.gridLan.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Código do Fornecedor"))
        item = self.gridLan.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Fornecedor"))
        item = self.gridLan.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Complemento"))
        item = self.gridLan.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Grupo do lançamento"))

        self.gridLan.setColumnHidden(4, True) # Ocultando a coluna de Código do Item
        self.gridLan.setColumnWidth(5, 200)   # Redimencionando a coluna de Item
        self.gridLan.setColumnHidden(7, True) # Ocultando a coluna de Código do Cliente
        self.gridLan.setColumnWidth(8, 200)   # Redimencionando a coluna de Cliente
        self.gridLan.setColumnHidden(9, True) # Ocultando a coluna de Código do Fornecedor
        self.gridLan.setColumnWidth(10, 200)  # Redimencionando a coluna de Fornecedor
        self.gridLan.setColumnWidth(11, 300)  # Redimencionando a coluna de Complemento
        self.gridLan.setColumnWidth(12, 200)  # Redimencionando a coluna de Grupo

    def get(self):
        return self.subLan
